// Generated by 搬砖工老刘 github.com/liujiahavefun
// DO NOT EDIT!
// Source: session.proto

package session

import (
	"cellnet"
)

func init() {

	// session.proto
	cellnet.RegisterMessageMeta("session.SessionAccepted", (*SessionAccepted)(nil), 2773618078)
	cellnet.RegisterMessageMeta("session.SessionAcceptFailed", (*SessionAcceptFailed)(nil), 712010276)
	cellnet.RegisterMessageMeta("session.SessionConnected", (*SessionConnected)(nil), 568839907)
	cellnet.RegisterMessageMeta("session.SessionConnectFailed", (*SessionConnectFailed)(nil), 133478244)
	cellnet.RegisterMessageMeta("session.SessionClosed", (*SessionClosed)(nil), 281454669)
	cellnet.RegisterMessageMeta("session.SessionError", (*SessionError)(nil), 2790591531)

}
